### ISSUE TITLE
An option to disable vega expressions

### ISSUE THREAD

**Issue by the21st** [vega/vega-embed#1081]
Vega's expression functions seem to be a large risk surface for anyone using vega-embed. Here's a recent example of an XSS vulnerability in vega: https://github.com/advisories/GHSA-4vq7-882g-wcg4

Is there a way to disable vega expressions when using `vega-embed` to minimize the security surface when embedding vega on our sites?

**Comment by domoritz** [comment]
I think Vega needs expression support to function. Do you have user provided specifications? If not, I don't think these XSS vulnerabilities that we fixed would even pose any issues. 

Either way, thus request is for Vega rather than embed since we only pass options down. I'll close this here but I'm happy to follow up on questions.
