### ISSUE TITLE
TypeError: Failed to fetch (Cordova)

### ISSUE THREAD

**Issue by nlafleur** [vega/vega-embed#153]
Trying to fetch a local .json spec in Cordova returns this error: 'Fetch API cannot load file:///D:/../../../../..json. URL scheme "file" is not supported.'

I had the same error when I tried to fetch my local application.json file, fixed this error by using 'new XMLHttpRequest' and parsing this new XMLHttpRequest responseText.

"vega": "^5.3.2",
"vega-embed": "^4.0.0",

**Comment by domoritz** [comment]
You need to set up a local web server and use a localhost URL. This is a browser restriction and we can't do anything about it.

**Comment by jheer** [comment]
I'm not sure I fully understood, so I did some Googling at it looks like Cordova is a node js environment for mobile apps: https://cordova.apache.org/

So it should in theory support file loading? But based on the error message it looks like the Fetch API was used rather than the node.js `fs` module -- is `fs` available within Cordova? Or is the wrong Vega build (one built for the browser, and so excluding `fs`) being used? If running in node, vega-embed might not be the right library to be using?

But again, I don't have a clear picture of the runtime environment.

**Comment by nlafleur** [comment]
Maybe I should've stated that I'm using NextJS, and came across this post: [https://github.com/zeit/next.js/issues/2734](url)
