### ISSUE TITLE
Enable custom "actions" in dropdown menu

### ISSUE THREAD

**Issue by SyntaxRules** [vega/vega-embed#156]
I would like to add my own links or javascript actions in the actions menu. Based off `embed.ts#L21` I believe these actions are hard coded. Is this something we are open too? Does anyone have an opinion on implementation?

https://github.com/vega/vega-embed/blob/1ea996fa8ebf56433cd2a2c09ba275c3b055d865/src/embed.ts#L21

**Comment by domoritz** [comment]
I'm definitely open to extending the actions menu. Do you have a specific use case?

**Comment by SyntaxRules** [comment]
The use case that brought me to opening this is as follows: In a web application we are generating these charts. We would like to include a link to "other versions" of this chart. This link leads to another page that shows different sizes or configurations of the chart so the user can download the one that will best work for them.

**Comment by danmarshall** [comment]
I would also like this feature. We'd like to open UI to help choose other data sources, and other specs. Since the dropdown exists, it's nice to extend instead of a second dropdown (or re-creating the existing actions in our own dropdown.)

**Comment by domoritz** [comment]
We can revive https://github.com/vega/vega-embed/pull/158. 

Before I merge anything, I'd like to know

* Can custom actions be achieved in some other way?
* What API do we want (that is flexible enough)?
* How do we make sure that we don't risk our users since embed options can be set via specs?

What do you think

**Comment by danmarshall** [comment]
[your comment on 158](https://github.com/vega/vega-embed/pull/158#issuecomment-539831133) is enlightening:
> I think this functionality can be achieved without modifying Vega-Embed. You can add any dom elements to the actions menu from outside embed

Let me try to do this via DOM and get back to you.

**Comment by danmarshall** [comment]
The DOM method 😉😉 works for me:
```js
await embed(el, spec);
const myAction = document.createElement('a');
myAction.textContent = "my action";
myAction.onclick = () => alert('hello');
```
Thanks Dom!

**Comment by domoritz** [comment]
It's a bit hacky but if it's okay, I'd like to keep embed lean.

**Comment by danmarshall** [comment]
Also, needed to close the dropdown afterwards: 
```js
myAction.onclick = () => {
  alert('hello');
  el.querySelector('details').removeAttribute('open');
};
```

**Comment by domoritz** [comment]
Closing as there is a workaround.

**Comment by benhammondmusic** [comment]
Is this still the best way to add extra functionality to the Actions menu in a Vega visualization?

**Comment by benhammondmusic** [comment]
> The DOM method 😉😉 works for me:
> 
> ```js
> await embed(el, spec);
> const myAction = document.createElement('a');
> myAction.textContent = "my action";
> myAction.onclick = () => alert('hello');
> el.querySelector('.vega-actions').appendChild(myAction);
> ```
> 
> Thanks Dom!

Hi, sorry if this is a dumb question but I've been struggling. I'm trying to make the actions menu more accessible by adding a focus state border (for keyboard / screen reader users), and eventually more functionality to the menu. I was trying to use this DOM manipulation hack discussed here (we are using `react-vega`). I'm not sure where to run this snippet of code (in a `useEffect()`? ), and what exactly is happening with the embed() function there where the `el` and `spec` arguments are coming from. Do I need to use a `ref` since I'm using React? 

This is the return method of our map component if it helps:

```
return (
    <div
      ref={ref}
      style={{
        width: "95%",
        margin: "auto",
      }}
    >
      {shouldRenderMap && (
        <Vega
          renderer="svg"
          spec={spec}
          width={width}
          // custom 3-dot options for states, hidden on territories
          actions={
            !props.hideActions && {
              export: { png: true, svg: true },
              source: false,
              compiled: false,
              editor: false,
            }
          }
          downloadFileName={`${props.filename} - Health Equity Tracker`}
          signalListeners={props.signalListeners}
        />
      )}
    </div>
  );
```

Thanks if anyone happens to read this!

**Comment by domoritz** [comment]
I'd be happy to add better accessibility right into the library. Feel free to send prs and I'll review.

**Comment by benhammondmusic** [comment]
> I'd be happy to add better accessibility right into the library. Feel free to send prs and I'll review. 

Thanks for the quick reply! I'll poke around and if I can get it working will submit a PR. Thanks!
