### ISSUE TITLE
Support absolute, hardcoded URLs when possible

### ISSUE THREAD

**Issue by willium** [vega/vega-embed#9]
Currently the links produced for "Open in Vega Editor" cannot be right clicked, etc. I believe in discussions with @domoritz and @kanitw I was told this was because of the limit in possible length of a URL. This number is around 2000 to support most browsers. 

Would it break user expectations if we build links and use get parameters when length allows (especially with vega-lite), and failover to the current implement for longer specs?

**Comment by domoritz** [comment]
This bugs me from time to time as well but given that we use post message, I don't see a way to fix this. Unfortunately [there are no real standards](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) but the de-facto standard is 2000.

**Comment by arvind** [comment]
Fair question! The current setup is less than ideal but we chose it because it provides a _consistent_ user experience (including a consistent experience of what works and does not work). If we were to implement the suggested functionality, I think knowing when a full URL would be produced would be opaque to the end-user and thus be more frustrating (e.g., "can I right click and open in a URL window for this spec or not?").
